version: "3.7"

services:
  web:
    build:
      context: .
    ports:
      - 4000:4000
    command: mix phx.server
    environment:
      MIX_ENV: dev
      PORT: 4000
    volumes:
      - .:/proj:cached
    depends_on:
      - db

  db:
    image: postgres:11
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data:cached

volumes:
  pg_data:
    driver: local
